theme = "autumn"

[editor]
auto-pairs = false
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[keys.insert]
C-a = "goto_line_end"

[keys.normal]
C-f = "file_picker_in_current_buffer_directory"

b = ["move_prev_word_start", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
x = "delete_selection"

D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
G = "goto_file_end"
p = ["paste_clipboard_after", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]

[keys.normal.c]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]

[keys.normal.d]
a = ["select_textobject_around"]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
p = ["replace_selections_with_clipboard", "collapse_selection"]
s = ["delete_selection", "insert_mode"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]

G = "goto_file_end"
